<a href="https://colab.research.google.com/github/mdnazmulislam0087/Tensorflow-Practice-me/blob/master/Hello_world_of_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

প্রথমে আমরা কেরাস এর মাধ্যমে হ্যালো ওয়ার্ল্ড প্রগ্রামিং শিখি ।


In [0]:
#প্রথমে আমরা টেনসরফ্লো এবং কেরাস ইম্পোরট করি 

import tensorflow as tf
from tensorflow import keras

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
xs= np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0],dtype=float)
print(xs)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
ys=np.array([11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0],dtype=float)
print(ys)

[11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [37]:
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Dense(1,activation=None,input_shape=[1]),
                               
])
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer="sgd", loss="mean_squared_error", metrics="acc")

In [40]:
model.fit(xs,ys,epochs=2)

Epoch 1/2
1/1 [==============================] - 0s 1ms/step - loss: 154.2180 - acc: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 967us/step - loss: 36.1178 - acc: 0.0000e+00


In [41]:
print(model.predict([12.0]))

[[27.701881]]


In [42]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
xs= np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0],dtype=float)
print(xs)
ys=np.array([11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0],dtype=float)
print(ys)
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Dense(1,activation=None,input_shape=[1]),
                               
])
model.summary()
model.compile(optimizer="sgd", loss="mean_squared_error", metrics="acc")
model.fit(xs,ys,epochs=100)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[11. 12. 13. 14. 15. 16. 17. 18. 19.]
Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 482.1488 - acc: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 75.5118 - acc: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 25.3455 - acc: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 19.0413 - acc: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 18.1351 - acc: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 17.8942 - acc: 0.0000e+00
Epoc

In [43]:
print(model.predict([12.0]))

[[27.653955]]


In [44]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
xs= np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0],dtype=float)
print(xs)
ys=np.array([11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0],dtype=float)
print(ys)
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Dense(1,activation=None,input_shape=[1]),
                               
])
model.summary()
model.compile(optimizer="sgd", loss="mean_squared_error", metrics="acc")
model.fit(xs,ys,epochs=1000)
print(model.predict([12.0]))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[11. 12. 13. 14. 15. 16. 17. 18. 19.]
Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 0s 1ms/step - loss: 590.1896 - acc: 0.0000e+00
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 88.5803 - acc: 0.0000e+00
Epoch 3/1000
1/1 [==============================] - 0s 1ms/step - loss: 26.7302 - acc: 0.0000e+00
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 18.9902 - acc: 0.0000e+00
Epoch 5/1000
1/1 [==============================] - 0s 1ms/step - loss: 17.9092 - acc: 0.0000e+00
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 17.6485 - acc: 0.0000e+0